# Bonds: Get time series - simple approach

In [20]:
import lseg.data as ld
import os
import pandas as pd

os.environ["LD_LIB_CONFIG_PATH"] = "../../Configuration"
ld.open_session()

The easiest way to get the time series is to use get_history()

In [21]:
start_date = "2026-01-01"
end_date = "2026-03-11"
ric = "US315890934="

df = ld.get_history(universe=ric,
                    interval="1D",
                    start=start_date,
                    end=end_date)
df

US315890934=,YLDTOMAT,BID_HIGH_1,OPEN_BID,BID_LOW_1,HIGH_YLD,LOW_YLD,MID_PRICE,A_YLD_1,ACCR_INT,ISMA_A_YLD,...,OIS_SPREAD,TED_SPREAD,INT_GV_SPD,REDEM_DATE,ASP6M,ASP3M,ASP1M,DIRTY_PRC,CLEAN_PRC,MAC_DURTN
Date,,,,,,,,,,,,,,,,,,,,,
2026-02-26,23.4834,97.12,97.12,97.12,23.4834,23.4834,97.62,19.4462,0.0,21.2765,...,1780.1506,<NA>,1980.2332,<NA>,1881.2402,1885.4256,1885.8015,97.12,97.12,0.2583
2026-02-27,27.6174,96.89,96.7,96.06,27.8236,24.4198,96.61,23.524,0.0,26.2336,...,2191.5321,<NA>,2394.7007,<NA>,2260.7898,2265.6899,2267.6702,96.11,96.11,0.2583
2026-03-02,24.1345,97.14,96.24,96.24,27.0821,23.4021,97.46,20.0884,0.0,22.0452,...,1844.2618,<NA>,2045.1259,<NA>,1942.9892,1946.8685,1945.7313,96.96,96.96,0.2583
2026-03-03,25.3182,96.8,96.59,96.19,27.2879,24.787,97.17,21.2561,0.0,23.4543,...,1961.2416,<NA>,2163.6797,<NA>,2049.4308,2054.7182,2055.1582,96.67,96.67,0.2583
2026-03-04,24.5421,97.2,96.73,96.73,25.0729,23.1584,97.36,20.4906,0.0,22.5288,...,1883.9132,<NA>,2085.8216,<NA>,1979.5484,1983.7421,1983.0396,96.86,96.86,0.2583
2026-03-05,23.8087,97.09,96.81,96.47,26.1373,23.6054,97.54,19.7671,0.0,21.6601,...,1811.4058,<NA>,2012.9749,<NA>,1912.8614,1917.0438,1915.1609,97.04,97.04,0.2583
2026-03-06,28.2776,97.09,97.09,95.95,28.2776,23.6054,96.45,24.1752,0.0,27.0422,...,2255.8525,<NA>,2461.1309,<NA>,2328.3873,2331.3382,2327.5638,95.95,95.95,0.2583
2026-03-09,22.3069,97.41,95.91,95.89,28.5256,22.3069,97.91,18.2856,0.0,19.8987,...,1661.7939,<NA>,1862.4593,<NA>,1775.9472,1778.4195,1764.6448,97.41,97.41,0.2583
2026-03-10,21.7205,97.8,97.43,97.43,22.3335,20.8238,98.08,17.6659,0.0333,19.1689,...,1601.4124,<NA>,1803.2918,<NA>,1719.8615,1722.8689,1720.7933,97.6133,97.58,0.2555
2026-03-11,21.0409,97.83,97.76,97.68,21.4115,20.7941,98.27,16.9535,0.0667,18.3349,...,1531.3159,<NA>,1735.0737,<NA>,1654.1428,1657.4005,1656.4818,97.8367,97.77,0.2527

_TODO:_ Get the right fields.

In [22]:
df: pd.DataFrame = ld.get_history(universe=ric,
                                  fields=["MID_PRICE"],
                                  interval="1D",
                                  start=start_date,
                                  end=end_date)
df

US315890934=  MID_PRICE
Date
2026-02-26        97.62
2026-02-27        96.61
2026-03-02        97.46
2026-03-03        97.17
2026-03-04        97.36
2026-03-05        97.54
2026-03-06        96.45
2026-03-09        97.91
2026-03-10        98.08
2026-03-11        98.27

In [23]:
ld.close_session()